### ISSUE TITLE
Ingeniería de Requerimientos

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Gregorio012#2]
[IngenieriaDeRequerimiento_GregorioOsorioSarmiento.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Gregorio012/files/10564145/IngenieriaDeRequerimiento_GregorioOsorioSarmiento.pdf)

**Comment by ang3-l32** [comment]
CALIFICACIÓN: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
